---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr) 
library(tidyr) 
library(ggplot2) 
library(readr)
library(usmap)
library(gridExtra)

library(biscale)
library(cowplot)
library(viridis) # viridis color scale
library(sf)

Children_TX <-read.csv("CData/Children_TX.csv")
Children_DFPS <-read.csv("CData/Children_DFPS.csv")
Adopt_Need <-read.csv("CData/Adopt_Need.csv")
Adopt_Need0 <-read.csv("CData/Adopt_Need0.csv") # Demographics by Region (County not available)
Homes <-read.csv("CData/Homes.csv")
PEI_Families_Served <-read.csv("CData/PEI_Families_Served.csv")
PEI_Expenditures <-read.csv("CData/PEI_Expenditures.csv")

Exits <-read.csv("CData/Exits.csv")
map_data <- read.csv("CData/map_data_cont.csv")
```

```{r}
# Children in DFPS Custody

# -------------------
# Plot 1A and 1B
# -------------------
Children_DFPS %>% group_by(Year, Age_Group) %>% summarise(Total = sum(Count)) %>% ggplot(aes(x =  Year, y = Total, fill = Age_Group)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=45)) + ggtitle("Number of Children in the State of Texas") + scale_fill_manual(values=c("#53b69c", "#238e9c", "#2e4873")) 

YourCounty = "Travis"
filter(Children_DFPS, County == YourCounty) %>% group_by(Year, Age_Group) %>% summarise(Total = sum(Count)) %>% ggplot(aes(x =  Year, y = Total, fill = Age_Group)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=45)) + ggtitle(paste("Number of Children in ",YourCounty," County",sep="")) + scale_fill_manual(name = "Age Group", values=c("#53b69c", "#238e9c", "#2e4873")) 

# -------------------
# Shiny App
# -------------------

# changing order of factors for plotting
Children_DFPS$Age_Group = as.factor(Children_DFPS$Age_Group)
Children_DFPS$Age_Group <- factor(Children_DFPS$Age_Group, levels = c("0 to 5 Years", "6 to 12 Years", "13 to 18 Years"))

Children_DFPS %>% filter(Year == "2020") %>% 
  group_by(Age_Group) %>% summarise(Total = sum(Count)) %>% ggplot(aes(x =  Age_Group, y = Total, fill = Age_Group)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=0)) + ggtitle("Number of Children in the State of Texas") + scale_fill_manual(values=c("#53b69c", "#238e9c", "#2e4873")) 

YourCounty = "Travis"
Children_DFPS %>% filter(Year == "2020") %>% 
filter(County == YourCounty) %>% group_by(Year, Age_Group) %>% summarise(Total = sum(Count)) %>% ggplot(aes(x =  Age_Group, y = Total, fill = Age_Group)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=0)) + ggtitle(paste("Number of Children in ",YourCounty," County",sep="")) + scale_fill_manual(values=c("#53b69c", "#238e9c", "#2e4873")) 

map_data_year <- filter(map_data, Year == "2020") 
plot_usmap(data = map_data_year, values = "DFPS_children_Total_County", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#ededed", high = "black", na.value = "white")
  scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Children in DFPS Legal Responsibility during 2020", 
         caption = "Data from data.texas.gov")


# -------------------
# Plot 2
# -------------------
map_data_year <- filter(map_data, Year == "2020") 

plot_usmap(data = map_data_year, values = "DFPS_children_Total_County", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#ededed", high = "black", na.value = "white")
  scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Children in DFPS Legal Responsibility during 2020", 
         caption = "Data from data.texas.gov")

# plot_usmap(data = tx_transformed, values = "Total_County", include = c("TX"), color = "black") + 
#   scale_fill_continuous(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
#
# plot_usmap(data = tx_transformed, values = "Total_Region", include = c("TX"), color = "black") + 
#   scale_fill_binned(name = "Total", breaks = sort(Adopt_Need_byRegion$Total_Region, decreasing = TRUE), na.value = "white")
# 
# plot_usmap(data = tx_transformed, values = "Total_Region", include = c("TX"), color = "black") + 
#   scale_fill_steps(n.breaks = 11, low = "grey", high = "brown", na.value = "white")
  
```

```{r}
# Homes

# Plot 1
Homes %>% group_by(Year, Type) %>% summarise(Total = sum(Count)) %>% ggplot(aes(x =  Year, y = Total, fill = Type)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=45)) + ggtitle("Foster/Adoptive Homes on Aug 31, 2020")

YourCounty = "Travis"
filter(Homes, County == YourCounty) %>% group_by(Year, Type) %>% summarise(Total = sum(Count)) %>% ggplot(aes(x =  Year, y = Total, fill = Type)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=45)) + ggtitle(paste("Number of Homes in ",YourCounty," County",sep="")) + scale_fill_manual(name = "Type", values=c("Red", "Blue", "Pink")) 

# Plot 2
map_data_year <- filter(map_data, Year == "2020") 

plot_usmap(data = map_data_year, values = "Homes_Total_County", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
  scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Foster/Adoptive Homes on Aug 31, 2020", 
         caption = "Data from data.texas.gov")

```

```{r}
PEI_Expenditures_long <- PEI_Expenditures %>% 
  pivot_longer(!Year, names_to = "Program", values_to = "Expenditures")

# changing order of factors for plotting
PEI_Expenditures_long$Program = as.factor(PEI_Expenditures_long$Program)
PEI_Expenditures_long$Program <- factor(PEI_Expenditures_long$Program, levels = c("HIP", "TNFP", "THV", "HOPES"))

# changing order of factors for plotting
PEI_Families_Served$Program = as.factor(PEI_Families_Served$Program)
PEI_Families_Served$Program <- factor(PEI_Families_Served$Program, levels = c("HIP", "TNFP", "THV", "HOPES"))

# Plot 1
PEI_Expenditures_long %>% group_by(Year, Program) %>% summarise(Total = sum(Expenditures, na.rm = TRUE)) %>% ggplot(aes(x =  Year, y = Total, fill = Program)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=45)) + ggtitle("PEI Expenditures")

# Plot 2
PEI_Families_Served$Program[PEI_Families_Served$Program %in% c("THV STATE","THV MIECHV")] <- "THV"

PEI_Families_Served %>% group_by(Year, Program) %>% summarise(Total = sum(Families_Served, na.rm = TRUE)) %>% ggplot(aes(x =  Year, y = Total, fill = Program)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(color="black", size=9, angle=45)) + ggtitle("PEI Families Served") + 
  xlim(2015, 2021)

# Plot 4
map_data_year <- filter(map_data, Year == "2020") 

plot_usmap(data = map_data_year, values = "Total_Families_Served_HOPES", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Families Served by HOPES", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_year, values = "Total_Families_Served_TNFP", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Families Served by TNFP", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_year, values = "Total_Families_Served_THV", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Families Served by THV", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_year, values = "Total_Families_Served_HIP", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "white") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Families Served by HIP", 
         caption = "Data from data.texas.gov")

```

```{r}
map_data_2014 <- filter(map_data, Year == "2014") 

plot_usmap(data = map_data_2014, values = "Physician_Access", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "red") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Physician Access", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_2014, values = "Uninsured.Rate", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "navy", high = "grey", na.value = "red") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Uninsured Rate", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_2014, values = "Graduation.Rate", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "red") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Graduation Rate", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_2014, values = "Personal.Income.per.Capita", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "red") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Personal.Income.per.Capita", 
         caption = "Data from data.texas.gov")

plot_usmap(data = map_data_2014, values = "Average.Wages", include = c("TX"), color = "black") + 
  #scale_fill_binned(name = "Total", low = "#b7d6ce", high = "#2e7265", na.value = "white")
    scale_fill_steps(name = "Total", n.breaks = 8, low = "grey", high = "navy", na.value = "red") +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Average.Wages", 
         caption = "Data from data.texas.gov")

```






