---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr) 
library(tidyr) 
library(ggplot2) 
library(readr)
library(maps)
library(usmap)
library(gridExtra)

library(biscale)
library(cowplot)
library(viridis) # viridis color scale
library(sf)

map_data <-read.csv("ShinyApp/CData/map_data_cont.csv")

theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(family = "Times", color = "#22211d"),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.border = element_blank(),
    ...
  )
}
```

```{r}
map_data_year <- filter(map_data, Year == "2020") 
data <- map_data_year
var1 = data$Adopt_Need_Total_County
var2 = data$Homes_Total_County

data$Adopt_Need_Total_County[is.na(data$Adopt_Need_Total_County)] <- 0
data$Homes_Total_County[is.na(data$Homes_Total_County)] <- 0
var1[is.na(var1)] <- 0
var2[is.na(var2)] <- 0

```



```{r}
ggplot(data, aes(x=var1)) + 
  geom_histogram()

ggplot(data, aes(x=var2)) + 
  geom_histogram() 
```


```{r}
# Variable 1
## Specified Breaks !!!!

pretty_breaks <- c(99.96,373.42)
# find the extremes
minVal <- min(var1, na.rm = T)
maxVal <- max(var1, na.rm = T)
# compute labels
labels <- c()
brks <- c(minVal, pretty_breaks, maxVal)
# round the labels (actually, only the extremes)
for(idx in 1:length(brks)){
  labels <- c(labels,round(brks[idx + 1], 2))
}

labels <- labels[1:length(labels)-1]
# define a new variable on the data set just as above
data$brks <- cut(var1, 
                     breaks = brks, 
                     include.lowest = TRUE, 
                     labels = labels)

brks_scale <- levels(data$brks)
labels_scale <- rev(brks_scale)

plot_usmap(data = data, values = "brks", include = c("TX"), color = "black") + 
  theme_map() +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "var1", 
         caption = "data from X and Y") +
  # now the discrete-option is used, 
  # and we use guide_legend instead of guide_colourbar
    scale_fill_manual(
          # in manual scales, one has to define colors, well, manually
          # I can directly access them using viridis' magma-function
          values = (magma(4)),
          breaks = rev(brks_scale),
          name = "Average age",
          drop = FALSE,
          labels = labels_scale,
          guide = guide_legend(
            direction = "horizontal",
            keyheight = unit(2, units = "mm"),
            keywidth = unit(70 / length(labels), units = "mm"),
            title.position = 'top',
            # I shift the labels around, the should be placed 
            # exactly at the right end of each legend key
            title.hjust = 0.5,
            label.hjust = 1,
            nrow = 1,
            byrow = T,
            # also the guide needs to be reversed
            reverse = T,
            label.position = "bottom"
  )) 

```
```{r}
# Variable 2
## Specified Breaks !!!!

pretty_breaks <- c(10,50.8)
# find the extremes
minVal <- min(var2, na.rm = T)
maxVal <- max(var2, na.rm = T)
# compute labels
labels <- c()
brks <- c(minVal, pretty_breaks, maxVal)
# round the labels (actually, only the extremes)
for(idx in 1:length(brks)){
  labels <- c(labels,round(brks[idx + 1], 2))
}

labels <- labels[1:length(labels)-1]
# define a new variable on the data set just as above
data$brks <- cut(var2, 
                     breaks = brks, 
                     include.lowest = TRUE, 
                     labels = labels)

brks_scale <- levels(data$brks)
labels_scale <- rev(brks_scale)

plot_usmap(data = data, values = "brks", include = c("TX"), color = "black") + 
  theme_map() +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "var2", 
         caption = "data from X and Y") +
  # now the discrete-option is used, 
  # and we use guide_legend instead of guide_colourbar
    scale_fill_manual(
          # in manual scales, one has to define colors, well, manually
          # I can directly access them using viridis' magma-function
          values = (magma(4)),
          breaks = rev(brks_scale),
          name = "Average age",
          drop = FALSE,
          labels = labels_scale,
          guide = guide_legend(
            direction = "horizontal",
            keyheight = unit(2, units = "mm"),
            keywidth = unit(70 / length(labels), units = "mm"),
            title.position = 'top',
            # I shift the labels around, the should be placed 
            # exactly at the right end of each legend key
            title.hjust = 0.5,
            label.hjust = 1,
            nrow = 1,
            byrow = T,
            # also the guide needs to be reversed
            reverse = T,
            label.position = "bottom"
  )) 
```



```{r}
# create 3 buckets for texas_homes
quantiles_var1 <- quantile(var1, 
                      probs = c(0,0.9632,0.9914,1), na.rm = TRUE)
# create 3 buckets for adoption need
quantiles_var2 <- quantile(var2, 
                      probs = c(0,0.90,0.9933,1), na.rm = TRUE)

# create color scale that encodes two variables
# red for homes and blue for adopt_need 
# the special notation with gather is due to readibility reasons
bivariate_color_scale <- tibble(
  "3 - 3" = "#3F2949", # high inequality, high income
  "2 - 3" = "#435786",
  "1 - 3" = "#4885C1", # low inequality, high income
  "3 - 2" = "#77324C",
  "2 - 2" = "#806A8A", # medium inequality, medium income
  "1 - 2" = "#89A1C8",
  "3 - 1" = "#AE3A4E", # high inequality, low income
  "2 - 1" = "#BC7C8F",
  "1 - 1" = "#CABED0" # low inequality, low income
) %>%
  gather("group", "fill")

# cut into groups defined above and join fill
bar <- data %>%
  mutate(
    var1_quantiles = cut(
      var1,
      breaks = quantiles_var1,
      include.lowest = TRUE
    ),
    var2_quantiles = cut(
      var2,
      breaks = quantiles_var2,
      include.lowest = TRUE
    ),
    # by pasting the factors together as numbers we match the groups defined
    # in the tibble bivariate_color_scale
    group = paste(
      as.numeric(var1_quantiles), "-",
      as.numeric(var2_quantiles)
    )
  ) %>%
  # we now join the actual hex values per "group"
  # so each municipality knows its hex value based on the his gini and avg
  # income value
  left_join(bivariate_color_scale, by = "group")

foo = bar %>% select(fips,fill)

# the special notation with gather is due to readibility reasons
colours = c("#3F2949","#435786","#4885C1","#77324C","#806A8A","#89A1C8","#AE3A4E","#BC7C8F","#CABED0")

#colours = bivariate_color_scale %>% select(fill)

## ----------------------------------------------------------------
map <- plot_usmap(data = foo, values = "fill", include = c("TX"), color = "black", ) + 
  theme_map() +
    labs(x = NULL, 
         y = NULL, 
         title = "Texas Counties", 
         subtitle = "Foster/Adoptive Homes Need", 
         caption = "Data from data.texas.gov") +
  # now the discrete-option is used, 
  # and we use guide_legend instead of guide_colourbar
    scale_fill_manual(
          # in manual scales, one has to define colors, well, manually
          # I can directly access them using viridis' magma-function
          values = colours,
          breaks = colours,
          name = "Foobar",
          drop = FALSE, na.value = "white") + theme(legend.position = "none")

map
```
```{r}
group = c("3 - 3", "2 - 3", "1 - 3", "3 - 2", "2 - 2", "1 - 2", "3 - 1","2 - 1", "1 - 1")
fill = c("#3F2949","#435786","#4885C1","#77324C","#806A8A","#89A1C8","#AE3A4E","#BC7C8F","#CABED0")

leg_data <- data.frame(group, fill)
  # "3 - 3" = "#3F2949", # high inequality, high income
  # "2 - 3" = "#435786",
  # "1 - 3" = "#4885C1", # low inequality, high income
  # "3 - 2" = "#77324C",
  # "2 - 2" = "#806A8A", # medium inequality, medium income
  # "1 - 2" = "#89A1C8",
  # "3 - 1" = "#AE3A4E", # high inequality, low income
  # "2 - 1" = "#BC7C8F",
  # "1 - 1" = "#CABED0" # low inequality, low income
```


```{r}
# separate the groups
leg_data %<>%
  separate(group, into = c("var1", "var2"), sep = " - ") %>%
  mutate(var1 = as.integer(var1),
         var2 = as.integer(var2))

legend <- ggplot() +
  geom_tile(
    data = leg_data,
    mapping = aes(
      x = var1,
      y = var2,
      fill = fill)
  ) +
  scale_fill_identity() +
  ylab("More Homes ->") +
  xlab(expression(atop("More Children Waiting", paste("for adoption ->")))) +
  theme(axis.ticks.y = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(), axis.text.y=element_blank(), 
        axis.title = element_text(size = 6)) + 
  #theme_map() +
  # quadratic tiles
  coord_fixed() 
  
legend
```

```{r}
ggdraw() +
  draw_plot(map, 0, 0, 1, 1) +
  draw_plot(legend, 0.05, 0.05, 0.3, 0.3) 
```

